version: "3.2"

volumes:
  mongodb:
  redis:
  sidekiq:

services:
  database:
    image: "docker.io/mongo:5"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

  cache:
    image: "docker.io/redis:7.4-alpine"
    ports:
      - "6380:6379"
    volumes:
      - "redis:/data"

  sidekiq:
    image: "docker.io/redis:7.4-alpine"
    ports:
      - "6381:6379"
    volumes:
      - "sidekiq:/data"

  web:
    image: "lucia-core:develop"
    build:
      context: ./
    env_file: ".env"
    environment:
      RAILS_ENV: "production"
      RAILS_LOG_TO_STDOUT: "1"
      UNICORN_SIDEKIQ: "1"
      REDIS_URL: "redis://redis_cache:6379/0"
      SIDEKIQ_REDIS_URL: "redis://redis_sidekiq:6379/0"
      MONGOID_SIGMA_HOST: "database:27017"
    ports:
      - "3000:3000"
    volumes:
      - "./tmp/container_log:/app/log"
    depends_on:
      - "database"
      - "redis_cache"
      - "redis_sidekiq"
