version: "3.2"

volumes:
  mongodb:
  redis:

services:
  database:
    image: "mongo:3"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

  redis:
    image: "redis:3-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
