version: "3.2"

volumes:
  mongodb:
  redis:
  sidekiq:

services:
  database:
    image: "docker.io/mongo:5"
    container_name: "lucia_core_db"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

  cache:
    image: "docker.io/redis:7.4-alpine"
    container_name: "lucia_core_cache"
    ports:
      - "6380:6379"
    volumes:
      - "redis:/data"

  sidekiq:
    image: "docker.io/redis:7.4-alpine"
    container_name: "lucia_core_sidekiq"
    ports:
      - "6381:6379"
    volumes:
      - "sidekiq:/data"

  web:
    image: "lucia-core:latest"
    container_name: "lucia_core_web"
    env_file: "../.env"
    environment:
      RAILS_ENV: "production"
      RAILS_LOG_TO_STDOUT: "1"
      UNICORN_SIDEKIQ: "1"
      REDIS_URL: "redis://cache:6379/0"
      SIDEKIQ_REDIS_URL: "redis://sidekiq:6379/0"
      MONGOID_SIGMA_HOST: "database:27017"
    ports:
      - "3000:3000"
    # volumes:
    #   - "../tmp/container_log:/app/log"
    depends_on:
      - "database"
      - "cache"
      - "sidekiq"
