default: &default
  # Sets if the authentication token can be immediately reused
  token_resuable: false

  # Time for the token reuse cache to expire, in seconds (min: 1)
  token_expiration_time: 60

  token_prefix: "lc-"

development:
  <<: *default
  token_expiration_time: 1

test:
  <<: *default

production:
  <<: *default
