development:
  clients:
    default:
      database: lucia
      hosts:
        - localhost:27017
    sigma:
      database: aurora
      hosts:
        - localhost:27017
  options:
    use_activesupport_time_zone: true
    use_utc: true
    app_name: LuciaCore

test:
  clients:
    default:
      database: lucia_core_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: lucia
      hosts:
        - localhost:27017
      options:
        user: <%= Rails.application.secrets.mongoid[:default][:user] %>
        password: <%= Rails.application.secrets.mongoid[:default][:password] %>
        roles:
          - 'dbOwner'
        auth_source: admin
    sigma:
      database: aurora
      hosts:
        - localhost:27017
      options:
        user: <%= Rails.application.secrets.mongoid[:sigma][:user] %>
        password: <%= Rails.application.secrets.mongoid[:sigma][:password] %>
        roles:
          - 'dbOwner'
        auth_source: admin
  options:
    use_activesupport_time_zone: true
    use_utc: true
    app_name: LuciaCore
