development:
  clients:
    default:
      database: lucia
      hosts:
        - localhost:27017
      options:
        # user: 'user'
        # password: 'password'
    sigma:
      database: aurora
      hosts:
        - localhost:27017
      options:
        # user: 'user'
        # password: 'password'
  options:
    use_activesupport_time_zone: true
    use_utc: true
    app_name: LuciaCore

test:
  clients:
    default:
      database: lucia_core_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
