# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  mongoid:
    default:
      user: <%= ENV["MONGOID_USER_DEFAULT"] %>
      password: <%= ENV["MONGOID_PASSWORD_DEFAULT"] %>
    sigma:
      user: <%= ENV["MONGOID_USER_SIGMA"] %>
      password: <%= ENV["MONGOID_PASSWORD_SIGMA"] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70d46b62752e6c5837c6352b63c0cfb6d31a3f9331aa841fca192c5128b0b2fda8fada9c5c31194c6127ebad51cbabcfe546f0e1f949587494dc86f01373f4f3

test:
  secret_key_base: 22a8778b38cba43ed84bd8572ffcc6617bf71f8dc3242979960ba17eb51c22b1493820e06f4d3212d60f3b02183ccdafa9911f7e5cc83e357cb15d563df60894

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
